# Generated by Django 4.2.10 on 2024-02-14 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_comment_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="bid",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="bid",
            name="bidby",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="bid",
            name="biddate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sporting Goods", "Sporting Goods"),
                    ("Toys & Hobbies", "Toys & Hobbies"),
                    ("Home & Garden", "Home & Garden"),
                    ("Jewelry & Watches", "Jewelry & Watches"),
                    ("Health & Beauty", "Health & Beauty"),
                    ("Business & Industrial", "Business & Industrial"),
                    ("Pet Supplies", "Pet Supplies"),
                    ("Baby Essentials", "Baby Essentials"),
                    ("Electronics", "Electronics"),
                    ("Collectibles & Art", "Collectibles & Art"),
                    ("Books, Movies, & Music", "Books, Movies, & Music"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="createdby",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="listing",
            name="createddate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.URLField(default=None),
        ),
    ]
