# Generated by Django 4.2.10 on 2024-02-14 01:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_bid_bid_bid_bidby_bid_biddate_listing_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="commentby",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="comment",
            name="commentdate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="commenttext",
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name="comment",
            name="item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
    ]
