# Generated by Django 4.2.10 on 2024-02-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_category_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="listing",
            name="currentbid",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="startingbid",
            field=models.FloatField(),
        ),
    ]
