# Generated by Django 4.2.10 on 2024-02-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_listing_category_alter_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="test",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
