# Generated by Django 4.2.10 on 2024-02-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_listing_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="test",
        ),
    ]
