# Generated by Django 4.2.10 on 2024-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="currentbid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="startingbid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
