# Generated by Django 4.2.10 on 2024-02-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
