# Generated by Django 4.2.10 on 2024-02-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_alter_bid_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="currentbid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
