# Generated by Django 4.2.10 on 2024-02-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0022_listing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(default="open", max_length=10),
        ),
    ]
