# Generated by Django 4.2.10 on 2024-02-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0023_alter_listing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="highestbidder",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
