# Generated by Django 4.2.10 on 2024-02-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0024_listing_highestbidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlistitem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
    ]
