# Generated by Django 4.2.10 on 2024-02-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0025_user_watchlistitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="watchlistitem",
        ),
    ]
