# Generated by Django 4.2.10 on 2024-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0027_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watcheditems",
            field=models.ManyToManyField(to="auctions.listing"),
        ),
    ]
