# Generated by Django 4.2.10 on 2024-02-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0028_user_watcheditems"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
