# Generated by Django 4.2.10 on 2024-02-15 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0029_delete_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="watcheditems",
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userwatchilst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watchlistitems",
                    models.ManyToManyField(blank=True, to="auctions.listing"),
                ),
            ],
        ),
    ]
