# Generated by Django 4.2.10 on 2024-02-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0030_remove_user_watcheditems_watchlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="userwatchilst",
            new_name="userwatchlist",
        ),
    ]
