# Generated by Django 4.2.10 on 2024-02-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0031_rename_userwatchilst_watchlist_userwatchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="watchlistitems",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="watchlistitems",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
    ]
