# Generated by Django 4.2.10 on 2024-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0032_remove_watchlist_watchlistitems_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="watchlistitems",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="watchlistitems",
            field=models.ManyToManyField(blank=True, to="auctions.listing"),
        ),
    ]
