# Generated by Django 4.2.10 on 2024-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0033_remove_watchlist_watchlistitems_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watchlistitems",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="auctions.listing"
            ),
        ),
    ]
