# Generated by Django 4.2.10 on 2024-02-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0034_alter_watchlist_watchlistitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to="auctions.listing"
            ),
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
